// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD19gxPBiildnNfXe2z1B-Tj4vHag8aaHI',
    appId: '1:599746693330:web:25575d7084f94abcb4050b',
    messagingSenderId: '599746693330',
    projectId: 'mahalaxmi-coolers',
    authDomain: 'mahalaxmi-coolers.firebaseapp.com',
    storageBucket: 'mahalaxmi-coolers.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXburakjXN7P-fbxTbfVB-r4iw-PsjIQs',
    appId: '1:599746693330:android:37d0d84f2dc03eb3b4050b',
    messagingSenderId: '599746693330',
    projectId: 'mahalaxmi-coolers',
    storageBucket: 'mahalaxmi-coolers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxzegjI5bKm3kiNHiF1d5eTF7WnHbX0DE',
    appId: '1:599746693330:ios:cf3a1d3ecc33cc05b4050b',
    messagingSenderId: '599746693330',
    projectId: 'mahalaxmi-coolers',
    storageBucket: 'mahalaxmi-coolers.firebasestorage.app',
    iosBundleId: 'com.example.mahalaxmiCoolers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxzegjI5bKm3kiNHiF1d5eTF7WnHbX0DE',
    appId: '1:599746693330:ios:cf3a1d3ecc33cc05b4050b',
    messagingSenderId: '599746693330',
    projectId: 'mahalaxmi-coolers',
    storageBucket: 'mahalaxmi-coolers.firebasestorage.app',
    iosBundleId: 'com.example.mahalaxmiCoolers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD19gxPBiildnNfXe2z1B-Tj4vHag8aaHI',
    appId: '1:599746693330:web:15864a0e485b66e4b4050b',
    messagingSenderId: '599746693330',
    projectId: 'mahalaxmi-coolers',
    authDomain: 'mahalaxmi-coolers.firebaseapp.com',
    storageBucket: 'mahalaxmi-coolers.firebasestorage.app',
  );
}
